default: &development

development:
  adapter: postgresql
  encoding: unicode
  database: inkplate_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: inkplate_test
  pool: 5

production:
  adapter: postgresql
  host: '<%= ENV["POSTGRES_HOST"] %>'
  username: '<%= ENV["POSTGRES_USERNAME"] %>'
  password: '<%= ENV["POSTGRES_PASSWORD"] %>'
  database: '<%= ENV["POSTGRES_DB"] %>'
  encoding: unicode
  pool: 25

